language: node_js
node_js:
- '9'
script: echo "No tests to run"
jobs:
  include:
  - name: deploy stable
    if: tag =~ ^((?!-\w).)*$
    deploy:
      provider: npm
      email: thomas.conner@me.com
      api_key:
        secure: LRVmr1gmR8b0a0EcJNfUMYLn3mkvyz9PIVW9UCjZ5QcFWpz3iGok13nBdZGVu3Axs8sFzUUzp3AdqESApIASKgV4+M2/mKGGAttjYpERJYSEY25F1+UwuoA1du3AnlAxAPBl6tgHc2AikMemYJL9AkTeb0Bb3V5l13WTsGxZy3KeJcWYPDzVDnl0+mGq36UJ+/MxDjKLpYq4QTHPb3wOAKeHG01i7Pn76/k/EhRFvzSZJwCNm3fdiNU8Ur84BGcTf3WvlNRVWmHeJcFuN7j//g9D9JBTah+whzUiNV5RS+9ob9yl3PrkKVadKKd1gaNdUNEsF9t4NtS8dKuYyzJmgPnD9d9fi4ehTAJvr+gu/n4XclRWh1CgGskw3yfGDMhU9Ry317S76w512vDaY8EYFvlftnZvF+JENxwHlFQXK5txJ9smHd18pL1HYWWvwCFZWkMf9rNwRgBbBYGbT+Spkp8lN7f65QvQsBqaOf6CyrlKB/beTWaC0h3/ouHEMNdCmI7e9dWTo2lrAbe6MnUm1Cuf6fKWBAeSlTeAfiwTSu+B1xA/m9RTIM1mvGrJ2m3GBoiKp6uxgzynxIy4ACwS2GKGrPDiBv5dH43xmQltXJBHfIjFlyfB7+Dt8VYr2YAobNuXqrJYk4GRrI6RMQhfvuLQPIRchmI01yuwWrCARe0=
      on:
        branch: master
        tags: true
  - name: deploy beta
    if: tag =~ ^v?([0-9])*\.[0-9]*\.[0-9]*-\w+$
    deploy:
      provider: npm
      tag: beta
      email: thomas.conner@me.com
      api_key:
        secure: LRVmr1gmR8b0a0EcJNfUMYLn3mkvyz9PIVW9UCjZ5QcFWpz3iGok13nBdZGVu3Axs8sFzUUzp3AdqESApIASKgV4+M2/mKGGAttjYpERJYSEY25F1+UwuoA1du3AnlAxAPBl6tgHc2AikMemYJL9AkTeb0Bb3V5l13WTsGxZy3KeJcWYPDzVDnl0+mGq36UJ+/MxDjKLpYq4QTHPb3wOAKeHG01i7Pn76/k/EhRFvzSZJwCNm3fdiNU8Ur84BGcTf3WvlNRVWmHeJcFuN7j//g9D9JBTah+whzUiNV5RS+9ob9yl3PrkKVadKKd1gaNdUNEsF9t4NtS8dKuYyzJmgPnD9d9fi4ehTAJvr+gu/n4XclRWh1CgGskw3yfGDMhU9Ry317S76w512vDaY8EYFvlftnZvF+JENxwHlFQXK5txJ9smHd18pL1HYWWvwCFZWkMf9rNwRgBbBYGbT+Spkp8lN7f65QvQsBqaOf6CyrlKB/beTWaC0h3/ouHEMNdCmI7e9dWTo2lrAbe6MnUm1Cuf6fKWBAeSlTeAfiwTSu+B1xA/m9RTIM1mvGrJ2m3GBoiKp6uxgzynxIy4ACwS2GKGrPDiBv5dH43xmQltXJBHfIjFlyfB7+Dt8VYr2YAobNuXqrJYk4GRrI6RMQhfvuLQPIRchmI01yuwWrCARe0=
      on:
        branch: master
        tags: true
