language: node_js
node_js:
- '9'
script: echo "No tests to run"
jobs:
  include:
  - name: deploy stable
    if: tag =~ ^((?!-\w).)*$
    deploy:
      provider: npm
      email: thomas.conner@me.com
      api_key:
        secure: dbGUeTc2PqSsH4MYgJ6aHeLGeDSWpRe+ASXsVi2LuBLZVl1uwWXjjZEa7TaWjw2Xcuf3buGvOrgirLjUPdhxVtexA38m1yAfk7NsHfQYaexJ1MU7aKy+GgbbKbFX3ZvRxyuG4gYu74j95avkJDye13aFz0eeUvMrU3fZQVJomDSffm8ZTya9jRnVFxRxOYTKswpe52XASZuveUUneqOC6zgmnj+3fbY7XlvxWXjwLx0PvOqvsO/S8L/kXBqRicpmxYc7qaFufdVWM+YhYupXjskZHjuZU3A6cfDV4o+HXuH0YDY3teXdN6TKeIU+STY5Xr1gS3sbFVeb9+kUSEGzWUbAyUesebv0XW/EcgSghbmp17E2MHn4B6pDf2OOl4sc2HbagNQdPVlxVX3YWwH852qkImENJvE3DYxgs5eijpH+gqA/idd/jyaCSQeiaIZSLNx3m7guF9hSgdIdmLA56q9cQEg835CVYgLrbebdeqqNhZUA/UEtH46mCtEOsKNq5qTcUX/BIYG9UFaOve+YM5mRhmgFVEDyoyjZPu1IK9wgX9cvY+Tgum88c/MOOmM9uSptqIgmYWT3isLzMYuzy9rl4psuBfiNYSdjN/a3IKeGGQnlP1M6ZsoVolzwMnf3AF5TdB+4eZ0fVqQdTXFVx7q89+JYrvjcWdSEWcvSuN8=
      on:
        all_branches: true
        tags: true
  - name: deploy beta
    if: tag =~ tag =~ ^v?([0-9])*\.[0-9]*\.[0-9]*-\w+$
    deploy:
      provider: npm
      tag: beta
      email: thomas.conner@me.com
      api_key:
        secure: dbGUeTc2PqSsH4MYgJ6aHeLGeDSWpRe+ASXsVi2LuBLZVl1uwWXjjZEa7TaWjw2Xcuf3buGvOrgirLjUPdhxVtexA38m1yAfk7NsHfQYaexJ1MU7aKy+GgbbKbFX3ZvRxyuG4gYu74j95avkJDye13aFz0eeUvMrU3fZQVJomDSffm8ZTya9jRnVFxRxOYTKswpe52XASZuveUUneqOC6zgmnj+3fbY7XlvxWXjwLx0PvOqvsO/S8L/kXBqRicpmxYc7qaFufdVWM+YhYupXjskZHjuZU3A6cfDV4o+HXuH0YDY3teXdN6TKeIU+STY5Xr1gS3sbFVeb9+kUSEGzWUbAyUesebv0XW/EcgSghbmp17E2MHn4B6pDf2OOl4sc2HbagNQdPVlxVX3YWwH852qkImENJvE3DYxgs5eijpH+gqA/idd/jyaCSQeiaIZSLNx3m7guF9hSgdIdmLA56q9cQEg835CVYgLrbebdeqqNhZUA/UEtH46mCtEOsKNq5qTcUX/BIYG9UFaOve+YM5mRhmgFVEDyoyjZPu1IK9wgX9cvY+Tgum88c/MOOmM9uSptqIgmYWT3isLzMYuzy9rl4psuBfiNYSdjN/a3IKeGGQnlP1M6ZsoVolzwMnf3AF5TdB+4eZ0fVqQdTXFVx7q89+JYrvjcWdSEWcvSuN8=
      on:
        all_branches: true
        tags: true
